### ISSUE TITLE
Update Functionality on New Tricycle Page

### ISSUE THREAD

**Issue by shayiii0714** [lunestelle/PHP_Sakaycle#15]
From - @lunestelle  | [PR](https://github.com/lunestelle/PHP_Sakaycle/pull/13/commits/7ed6650a1190dfd929b8144a90337a534397fccb) | [Github Issue](https://github.com/lunestelle/PHP_Sakaycle/pull/13)
-  Fixed issue where in the tricycle_id is not being saved to the documents table.
- Updated `make_model` input field to a dropdown and when the user selected option `Others`, the user will be able to input the specific model.
- When choosing a color code, the zone will automatically fill out.
   - Made the route area input field a read-only, so it will only be filled once a color code is selected.

**Comment by lunestelle** [comment]
### New Tricycle Update Functionality and Made the Taripa Table use datatables:
- Separate the column of the Student Rate and Senior Citizen and PWD Rate
- Updated the controller and view on the `new_tricyle` feature based on the update on `taripa`

![image](https://github.com/lunestelle/PHP_Sakaycle/assets/119985247/ed4d4f9d-af22-4b0e-9eac-9285b3a4c2b5)

PR: https://github.com/lunestelle/PHP_Sakaycle/pull/13/commits/4dda9a0399e8eb87e894f800d6a78369a0138851

@shayiii0714
